# Generated by Django 4.2.7 on 2023-11-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_test_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='question_count',
        ),
    ]
