# Generated by Django 4.2.7 on 2023-11-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_test_question_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='courses.course'),
        ),
    ]
