# Generated by Django 4.2.7 on 2023-11-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_test_questions_alter_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
