# Generated by Django 4.2.7 on 2023-11-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_usercourse_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='viewed',
            new_name='completed',
        ),
    ]
