# Generated by Django 4.2.7 on 2023-11-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_rename_viewed_usercourse_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='completed',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Complete', 'Complete')], default='Active', max_length=10),
        ),
    ]
