# Generated by Django 4.2.7 on 2023-11-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_usercourse_completed_usercourse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
