# Generated by Django 4.2.7 on 2023-11-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_usercourse_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='viewed',
        ),
    ]
