# Generated by Django 4.2.7 on 2023-11-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_couponcode_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcode',
            name='discount',
        ),
    ]
