# Generated by Django 4.2.7 on 2023-11-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_couponcode_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='length',
        ),
        migrations.RemoveField(
            model_name='course',
            name='resource',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
