# Generated by Django 4.2.7 on 2023-11-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_course_length_remove_course_resource_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
    ]
