# Generated by Django 4.2.7 on 2023-11-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_course_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisite',
            name='course',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='course',
        ),
        migrations.DeleteModel(
            name='Learning',
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
