# Generated by Django 4.2.7 on 2023-11-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_learning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
