# Generated by Django 4.2.7 on 2023-11-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='files/avatars/default.png', upload_to='files/avatars/'),
        ),
    ]
