# Generated by Django 4.2.7 on 2023-11-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
