# Generated by Django 4.2.7 on 2023-11-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_course_thumbnail_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='courses/avatars/default.png', upload_to='courses/files/avatars'),
        ),
    ]
