# Generated by Django 4.2.7 on 2023-11-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='files/thumbnail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='files/avatars/default.png', upload_to='files/avatars/'),
        ),
    ]
