# Generated by Django 3.1.4 on 2025-03-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_auto_20250311_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
            ],
        ),
    ]
