# Generated by Django 3.1.4 on 2025-03-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='coin_rate',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
    ]
