# Generated by Django 3.1.4 on 2025-03-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_auto_20250311_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='coin_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
