# Generated by Django 3.1.4 on 2025-03-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_auto_20250311_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Баланс', 'verbose_name_plural': 'Баланс'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Курс обміну монет', 'verbose_name_plural': 'Курс обміну монет'},
        ),
    ]
