# Generated by Django 3.1.4 on 2025-03-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_auto_20250312_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placementanswer',
            options={'verbose_name': 'Відповіді до тесту', 'verbose_name_plural': 'Відповіді до тесту'},
        ),
        migrations.AlterModelOptions(
            name='placementquestion',
            options={'verbose_name': 'Питання до тесту', 'verbose_name_plural': 'Питання до тесту'},
        ),
        migrations.AlterModelOptions(
            name='placementtest',
            options={'verbose_name': 'Тест на рівень', 'verbose_name_plural': 'Тест на рівень'},
        ),
    ]
