# Generated by Django 3.1.4 on 2025-03-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_auto_20250312_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.placementquestion'),
        ),
    ]
