# Generated by Django 3.1.4 on 2025-03-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_auto_20250312_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=200),
        ),
    ]
