# Generated by Django 3.1.4 on 2025-03-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_auto_20250322_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementtest',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian'), ('cz', 'Czech'), ('tu', 'Turkish'), ('ch', 'Chinese'), ('fr', 'French')], default='en', max_length=2),
        ),
    ]
