# Generated by Django 3.1.4 on 2025-03-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_auto_20250322_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='start_test',
            field=models.BooleanField(default=False),
        ),
    ]
