# Generated by Django 3.1.4 on 2025-04-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_profile_start_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Викладач')], default='student', max_length=10),
        ),
    ]
