# Generated by Django 3.1.4 on 2025-04-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Студент', 'Студент'), ('Викладач', 'Викладач')], default='Студент', max_length=10),
        ),
    ]
