# Generated by Django 3.1.4 on 2025-04-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_auto_20250428_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placementanswer',
            options={'verbose_name': 'Відповідь', 'verbose_name_plural': 'Відповіді'},
        ),
        migrations.AlterModelOptions(
            name='placementtest',
            options={'verbose_name': 'Тест на рівень', 'verbose_name_plural': 'Тести на рівень'},
        ),
        migrations.RemoveField(
            model_name='placementquestion',
            name='test',
        ),
        migrations.AddField(
            model_name='placementtest',
            name='questions',
            field=models.ManyToManyField(related_name='tests', to='courses.PlacementQuestion'),
        ),
    ]
