# Generated by Django 3.1.4 on 2025-05-07 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_auto_20250428_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.profile'),
        ),
    ]
