# Generated by Django 3.1.4 on 2025-05-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_auto_20250507_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(related_name='students', through='courses.UserCourse', to='courses.Course'),
        ),
    ]
