# Generated by Django 3.1.4 on 2025-05-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_profile_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.profile'),
        ),
    ]
