# Generated by Django 3.1.4 on 2025-05-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_auto_20250507_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='students', through='courses.UserCourse', to='courses.Course'),
        ),
    ]
