# Generated by Django 3.1.4 on 2025-05-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0065_auto_20250507_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(related_name='students', through='courses.UserCourse', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.profile'),
        ),
    ]
